window.artbydkdata = {
	art: [
	    {
	        id: 15,
	        title: "Queen Elizabeth II",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Queen Elizabeth II",
	        type: "Black and White Portrait",
	        size: "18\" x 24\"",
	        infobox_id: "liz",
	        original_img: "lizzy-1.jpg",
	        painting_sm: "lizzy_sm_2.8.jpg",
	        painting_lg: "m/lizzy.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 14,
	        title: "Jenner Jenner",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Kendall Jenner",
	        type: "Black and White Portrait",
	        size: "18\" x 24\"",
	        infobox_id: "jj",
	        original_img: "jj.jpg",
	        painting_sm: "jjen.jpg",
	        painting_lg: "m/jjenner.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 13,
	        title: "PUG",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Taylor Swift",
	        type: "Black and White Portrait",
	        size: "18\" x 24\"",
	        infobox_id: "pug",
	        original_img: "pug1.jpg",
	        painting_sm: "pug.jpg",
	        painting_lg: "m/pug.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 12,
	        title: "Thumbs Up",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Sugar",
	        type: "Black and White Portrait",
	        size: "16\" x 20\"",
	        infobox_id: "thumb",
	        original_img: "thumbsup1.jpg",
	        painting_sm: "thumbsup.jpg",
	        painting_lg: "m/thumbsup.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 11,
	        title: "Marilyn",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Marilyn Munroe",
	        type: "Black and White Portrait",
	        size: "16\" x 20\"",
	        infobox_id: "marilyn",
	        original_img: "marilyn1.jpg",
	        painting_sm: "marilyn.jpg",
	        painting_lg: "m/marilyn.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 10,
	        title: "Sexy Hat Tip Girl",
	        status: "completed",
	        medium: "Acrylic on Wood Panel",
	        subject: "Sugar",
	        type: "Black and White Portrait",
	        size: "14\" x 24\"",
	        infobox_id: "shtg",
	        original_img: "shtg1.jpg",
	        painting_sm: "shtg.jpg",
	        painting_lg: "shtg.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 9,
	        title: "Lady in Red",
	        status: "completed",
	        medium: "Acrylic on Wood Panel",
	        subject: "Sugar",
	        type: "Black and White Portrait",
	        size: "14\" x 28\"",
	        infobox_id: "red",
	        original_img: "ladyinred1.jpg",
	        painting_sm: "ladyinred.jpg",
	        painting_lg: "ladyinred.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 8,
	        title: "Nina",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Nina Simone",
	        type: "Black and White Portrait",
	        size: "20\" x 16\"",
	        infobox_id: "nina",
	        original_img: "nina1.jpg",
	        painting_sm: "nina.jpg",
	        painting_lg: "nina.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 7,
	        title: "Pinks",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Gereta Anderson",
	        type: "Color Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "pinks",
	        original_img: "pinks1.jpg",
	        painting_sm: "pinks.jpg",
	        painting_lg: "pinks.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 6,
	        title: "Bob",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Bob Marley",
	        type: "Black and White Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "bob",
	        original_img: "bob1.jpg",
	        painting_sm: "bob.jpg",
	        painting_lg: "bob.jpg",
	        orientation: "portrait"
	    },

	    {
	        id: 1,
	        title: "Beauty",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Emma Watsonn",
	        type: "Black and White Portrait",
	        size: "24\" x 18\"",
	        infobox_id: "emma",
	        original_img: "em.jpg",
	        painting_sm: "em1_3.jpg",
	        painting_lg: "m/em1_3.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 2,
	        title: "Nicole",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Nicole Kidman",
	        type: "Black and White Portrait",
	        size: "24\" x 18\"",
	        infobox_id: "nicole",
	        original_img: "nicole.jpg",
	        painting_sm: "nicole1_7.jpg",
	        painting_lg: "m/nicole1_7.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 3,
	        title: "Bad Berry",
	        status: "Completed",
	        medium: "Acrylic on canvas",
	        subject: "Halle Berry",
	        type: "Black and White Portrait",
	        size: "16\" x 20\"",
	        infobox_id: "halle",
	        original_img: "halle1.jpg",
	        painting_sm: "halle1_9.jpg",
	        painting_lg: "m/halle1_9.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 4,
	        title: "Flower Face",
	        status: "Completed",
	        medium: "Acrylic on canvas",
	        subject: "Cara Delevingne",
	        type: "Black and White Portrait",
	        size: "24\" x 18\"",
	        infobox_id: "cara",
	        original_img: "cara1.jpg",
	        painting_sm: "cara.jpg",
	        painting_lg: "cara.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 5,
	        title: "Charlize",
	        status: "Completed",
	        medium: "Acrylic on canvas",
	        subject: "Charlize Theron",
	        type: "Black and White Portrait",
	        size: "20\" x 24\"",
	        infobox_id: "charlize",
	        original_img: "charlize_1.jpg",
	        painting_sm: "charlize1_8.jpg",
	        painting_lg: "m/charlize1_8.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 16,
	        title: "Central Park",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Central Park",
	        type: "Color Landscape",
	        size: "14\" x 11\"",
	        infobox_id: "cp",
	        original_img: "central_park_s.jpg",
	        painting_sm: "central_park_s.jpg",
	        painting_lg: "m/central_park_m.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 17,
	        title: "Cherish",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Love",
	        type: "Color Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "cherish",
	        original_img: "cherish1.jpg",
	        painting_sm: "cherish.jpg",
	        painting_lg: "m/cherish-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 18,
	        title: "Elvis",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Elvis Presley",
	        type: "Black and White Portrait",
	        size: "16\" x 20\"",
	        infobox_id: "elvis",
	        original_img: "elvis1.jpg",
	        painting_sm: "elvis.jpg",
	        painting_lg: "m/elvis-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 19,
	        title: "Frozen",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Fantasy",
	        type: "Color Portrait",
	        size: "14\" x 11\"",
	        infobox_id: "frozen",
	        original_img: "frozen.jpg",
	        painting_sm: "frozen.jpg",
	        painting_lg: "m/frozen-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 20,
	        title: "Kiss of Life",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Love",
	        type: "Color Portrait",
	        size: "14\" x 11\"",
	        infobox_id: "kol",
	        original_img: "kol.jpg",
	        painting_sm: "kiss_of_life_p1.jpg",
	        painting_lg: "m/kiss_of_life_p1.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 21,
	        title: "Kiss of Life Part 2",
	        status: "completed",
	        medium: "Acrylic and Pastel on canvas",
	        subject: "Love",
	        type: "Color Portrait",
	        size: "14\" x 11\"",
	        infobox_id: "kol2",
	        original_img: "kol2.jpg",
	        painting_sm: "kiss_of_life_p2.jpg",
	        painting_lg: "m/kiss_of_life_p2.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 22,
	        title: "Kiss of Life Part 3",
	        status: "completed",
	        medium: "Acrylic and Graphite on canvas",
	        subject: "Love",
	        type: "Color Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "kol3",
	        original_img: "kol3.jpg",
	        painting_sm: "kiss_of_life_p3.jpg",
	        painting_lg: "m/kiss_of_life_p3.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 23,
	        title: "Morning Star",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Tariq Anderson",
	        type: "Color Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "kid",
	        original_img: "morning_star1.jpg",
	        painting_sm: "morning_star.jpg",
	        painting_lg: "m/morning_star-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 24,
	        title: "One Sweet Day",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Dreams of Love",
	        type: "Color Portrait",
	        size: "14\" x 11\"",
	        infobox_id: "sweet",
	        original_img: "one_sweet_day1.jpg",
	        painting_sm: "one_sweet_day.jpg",
	        painting_lg: "m/one_sweet_day-1.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 25,
	        title: "Rising Sun",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Imagination",
	        type: "Color Portrait",
	        size: "14\" x 11\"",
	        infobox_id: "sun",
	        original_img: "rising_sun.jpg",
	        painting_sm: "rising_sun.jpg",
	        painting_lg: "m/rising_sun-1.jpg",
	        orientation: "landscape"
	    },
	    {
	        id: 26,
	        title: "Sacred Rose",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Love",
	        type: "Color Still Life",
	        size: "11\" x 14\"",
	        infobox_id: "rose",
	        original_img: "sacred_rose1.jpg",
	        painting_sm: "sacred_rose.jpg",
	        painting_lg: "m/sacred_rose-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 27,
	        title: "The Wolf",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Wolfman",
	        type: "Black and White Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "wolf",
	        original_img: "the_wolf1.jpg",
	        painting_sm: "the_wolf.jpg",
	        painting_lg: "m/the_wolf-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 28,
	        title: "Sexy Hat Tip Girl",
	        status: "completed",
	        medium: "Acrylic on canvas",
	        subject: "Sugar",
	        type: "Black and White Portrait",
	        size: "11\" x 14\"",
	        infobox_id: "shtg2",
	        original_img: "shtg1_p1.jpg",
	        painting_sm: "shtg_p1.jpg",
	        painting_lg: "m/shtg1_p1-1.jpg",
	        orientation: "portrait"
	    },
	    {
	        id: 29,
	        title: "Sin City",
	        status: "completed",
	        medium: "Acrylic on Wood Panel",
	        subject: "Imagination",
	        type: "Colir / Black and White Mixed",
	        size: "37\" x 24\"",
	        infobox_id: "sc",
	        original_img: "sc.jpg",
	        painting_sm: "sc.jpg",
	        painting_lg: "m/sc.jpg",
	        orientation: "portrait"
	    }
	],

	bio: {
		title: "The Basics",
		popWords: ["Creativity"],
		content : ": the ability to transcend traditional ideas, rules, patterns, relationships, or the like, and to create meaningful new ideas, forms, methods, interpretations, etc.; originality, progressiveness, or imagination. That is how <a href=\"http://www.dictionary.com/\">dictionary.com</a> defines creativity, I love everything about that. Something about taking emptiness and filling it with something meaningful, a spark that may be ephemeral or eternal but if you create for even a second. You change the world as you know it. I am Duane K. Anderson founder and owner of DKAnderson Designs LLC a nerd, adventurer, poet, painter, lover of life and true believer in the immutable power of the human spirit. Thank you for stopping by."
	},

	deck: {
		title: "",
		subtitle: "",
		working: {
			title: "Angel in a Cave",
			description: "Of deep personal significance to me, it represents a real turning point in my life, a moment that can only be descibed as light rushing into a dark cave and the wings of an angel, love, light and an ocean. What more does a guy need.",
			imageUrl: "angel.jpg",
			specs: {
				subject: "LadyFit",
				medium: "Acrylic on canvas",
		        type: "Black and White Portrait",
		        size: "11\" x 14\""
			}
		},

		next: {
			title: "tulip",
			description: "Stiill in transit through time and space, my mind and its future place.",
			imageUrl: "tulip.jpg",
			specs: {
				"subject": "Dua Lipa",
				"medium": "Acrylic on canvas",
		        "type": "Black and White Portrait",
		        "size": "11\" x 14\""
			}
		},

		reading: {
			title: "Light",
			subtitle: "A Radiant History from Creation to the Quantum Age",
			description: "As an artist and amateur scientist, or so I tell myself. I am fascinated with light, I found this book in the library, I know nothing of the author except he's writen one of the most beautiful introductions I have ever read and I can't wait to hear the rest.",
			author: "Bruce Watson",
			thumb: "lightBook1.jpg",
			imageUrl: "lightBook.jpg",
			url: ""
		}
	},

	specials: [
		    {
		      title: "Daisy",
		      status: "work in progress",
		      medium: "Acrylic on canvas",
		      subject: "Taylor Swift",
		      type: "Black and white portrait",
		      size: "11\" x 14\"",
		      orientation: "portrait",
		      price: "6500",
		      url: "daisy.jpg",
		      description: "\"I once was poison ivy but now I am your daisy\", inspired by her own words and the triumph and beauty she represents to her fans all over the world, a flower, a light and a queen",
		      id: 1
		    },
		    {
		      title: "Angel",
		      status: "work in progress",
		      medium: "Acrylic on canvas",
		      subject: "Lady Fit",
		      type: "Black and white portrait",
		      size: "11\" x 14\"",
		      orientation: "porttrait",
		      price: "6500",
		      url: "angel.jpg",
		      description: "Of deep personal significance to me, it represents a real turning point in my life, a moment that can only be descibed as light rushing into a dark cave and the wings of an angel, love, light and an ocean. What more does a guy need.",
		      id: 2
		    },
		    {
		      title: "Flower",
		      status: "completed",
		      medium: "Acrylic on canvas",
		      subject: "Kendall Jenner",
		      type: "Black and white portrait",
		      size: "11\" x 14\"",
		      orientation: "porttrait",
		      price: "6500",
		      url: "flower.jpg",
		      description: "\"Natures first green is gold, her hardest hue to hold, her early leaf's a flower but only so an hour\", from Robert Frost's poem, Nothing Gold Can Stay a tribute to the fragility of beauty, innocence and youth, a celebration of its secrets and a woman who encapsulates them all.",
		      id: 3
		    },
		    {
		      title: "Tulip",
		      status: "completed",
		      medium: "acrylic on canvas",
		      subject: "Dua Lipa",
		      type: "black and white portrait",
		      size: "11\" x 14\"",
		      orientation: "porttrait",
		      price: "6500",
		      url: "tulip.jpg",
		      description: "Stiill in transit through time and space, my mind and its future place.",
		      id: 4
		    },
		    {
		      title: "Kids",
		      status: "completed",
		      medium: "acrylic on canvas",
		      subject: "Berlin Wall Kids",
		      type: "black and white portrait",
		      size: "14\" x 11\"",
		      orientation: "lanscape",
		      price: "5000",
		      url: "kids.jpg",
		      description: "Barriers to love, to peace, to freedom, to prosperity and far too often to the truth, obdurate fences around haunting romances and the view from above it all, in defiance",
		      id: 5
		    }
		  ]
}